path: /data

train: images/train

val: images/train

names:
  0: бортпроводник(женский пол)
  1: платье
  2: блуза кор.рукав,брюки
  3: блуза,жакет,брюки
  4: пилотка
  5: шейный платок
  6: жакет
  7: бейдж
  8: пропуск
  9: ремень
  10: блуза кор.рукав,юбка
  11: блуза,жакет,юбка
  12: блуза кор.рукав,жилет кост.,юбка
  13: туфли
  14: жакет,брюки
  15: блуза дл.рукав,жилет кост.,юбка
  16: перчатки
  17: колготы
  18: короткая юбка(нарушение)
  19: кольцо
  20: серьги
  21: цепочка(нарушение)
  22: бейдж(нарушение)
  23: часы
  24: очки
  25: ремень(нарушение)
  26: сумка
  27: жакет,юбка
  28: жилет трик.
  29: платье,жакет
  30: шейный платок(нарушение)
  31: часы(нарушение)
  32: браслет(нарушение)
  33: колготы(нарушение)
  34: туфли(нарушение)
  35: серьги(нарушение)
  36: жакет(нарушение)
  37: блузка кор.рукав,жилет трик.,юбка(нарушение)
  38: расстегнутая одежда(нарушение)
  39: блуза кор.рукав,брюки,жилет трик.
  40: блуза кор.рукав,брюки,жилет кост.
  41: блуза дл.рукав,брюки
  42: блуза дл.рукав,жилет трик.,брюки
  43: блуза дл.рукав,жилет кост.,брюки
  44: блуза дл.рукав,жилет трик.,юбка
  45: предмет в кармане(нарушение)
  46: неопрятно(нарушение)
  47: грязь,повреждение(нарушение)
  48: жилет кост.
  49: бортпроводник(мужской пол)
  50: пилот(мужской пол)
  51: пилотка(нарушение)
  52: блуза дл.рукав,юбка

colors:
  0:
    - 255
    - 0
    - 255
  1:
    - 139
    - 0
    - 0
  2:
    - 139
    - 0
    - 0
  3:
    - 74
    - 148
    - 68
  4:
    - 0
    - 255
    - 255
  5:
    - 255
    - 255
    - 0
  6:
    - 74
    - 148
    - 68
  7:
    - 74
    - 148
    - 68
  8:
    - 74
    - 148
    - 68
  9:
    - 74
    - 148
    - 68
  10:
    - 74
    - 148
    - 68
  11:
    - 74
    - 148
    - 68
  12:
    - 74
    - 148
    - 68
  13:
    - 79
    - 79
    - 47
  14:
    - 74
    - 148
    - 68
  15:
    - 74
    - 148
    - 68
  16:
    - 74
    - 148
    - 68
  17:
    - 74
    - 148
    - 68
  18:
    - 74
    - 148
    - 68
  19:
    - 74
    - 148
    - 68
  20:
    - 20
    - 70
    - 140
  21:
    - 50
    - 30
    - 196
  22:
    - 74
    - 148
    - 68
  23:
    - 74
    - 148
    - 68
  24:
    - 58
    - 30
    - 196
  25:
    - 74
    - 148
    - 68
  26:
    - 74
    - 148
    - 68
  27:
    - 74
    - 148
    - 68
  28:
    - 50
    - 30
    - 196
  29:
    - 74
    - 148
    - 68
  30:
    - 74
    - 148
    - 68
  31:
    - 74
    - 148
    - 68
  32:
    - 74
    - 148
    - 68
  33:
    - 58
    - 30
    - 196
  34:
    - 58
    - 30
    - 196
  35:
    - 58
    - 30
    - 196
  36:
    - 58
    - 30
    - 196
  37:
    - 58
    - 30
    - 196
  38:
    - 58
    - 30
    - 196
  39:
    - 58
    - 30
    - 196
  40:
    - 58
    - 30
    - 196
  41:
    - 58
    - 30
    - 196
  42:
    - 58
    - 30
    - 196
  43:
    - 74
    - 148
    - 68
  44:
    - 74
    - 148
    - 68
  45:
    - 74
    - 148
    - 68
  46:
    - 74
    - 148
    - 68
  47:
    - 74
    - 148
    - 68
  48:
    - 74
    - 148
    - 68
  49:
    - 58
    - 30
    - 196
  50:
    - 58
    - 30
    - 196
  51:
    - 58
    - 30
    - 196
  52:
    - 74
    - 148
    - 68

model_names:
  - rivc-cnn-standart-0.3

model_files:
  - yolov8s90_1600_130623.pt

uniform:
  general_summer_outside_steward_woman:
    - бортпроводник(женский пол)
    - пилотка
    - бейдж
    - туфли
    - шейный платок
    - блуза
    - жакет
    - юбка
    
uniform_consist:
  - бортпроводник(женский пол)
  - жакет
  - платье
  - юбка
  - брюки
  - блуза
  - блуза дл.рукав
  - блуза кор.рукав
  - жилет кост.
  - жилет трик.
  - пилотка
  - ремень
  - шейный платок
  - туфли
  - бейдж
  - пропуск
  - часы
  - колготы
  - серьги
  - кольцо
  - плащ
  - пальто
  - шапка зимняя
  - шарф
  - перчатки
  - сапоги
  - зажим для галстука
  - очки
  - линзы
  - сумка
  - зонт

valid_names:
  0: бортпроводник(женский пол)
  1: платье
  2: блуза кор.рукав,брюки
  3: блуза,жакет,брюки
  4: пилотка
  5: шейный платок
  6: жакет
  7: бейдж
  8: пропуск
  9: ремень
  10: блуза кор.рукав,юбка
  11: блуза,жакет,юбка
  12: блуза кор.рукав,жилет кост.,юбка
  13: туфли
  14: жакет,брюки
  15: блуза дл.рукав,жилет кост.,юбка
  16: перчатки
  17: колготы
  18: короткая юбка(нарушение)
  19: кольцо
  20: серьги
  21: цепочка(нарушение)
  22: бейдж(нарушение)
  23: часы
  24: очки
  25: ремень(нарушение)
  26: сумка
  27: жакет,юбка
  28: жилет трик.
  29: платье,жакет
  30: шейный платок(нарушение)
  31: часы(нарушение)
  32: браслет(нарушение)
  33: колготы(нарушение)
  34: туфли(нарушение)
  35: серьги(нарушение)
  36: жакет(нарушение)
  37: блузка кор.рукав,жилет трик.,юбка(нарушение)
  38: расстегнутая одежда(нарушение)
  39: блуза кор.рукав,брюки,жилет трик.
  40: блуза кор.рукав,брюки,жилет кост.
  41: блуза дл.рукав,брюки
  42: блуза дл.рукав,жилет трик.,брюки
  43: блуза дл.рукав,жилет кост.,брюки
  44: блуза дл.рукав,жилет трик.,юбка
  45: предмет в кармане(нарушение)
  46: неопрятно(нарушение)
  47: грязь,повреждение(нарушение)
  48: жилет кост.
  49: бортпроводник(мужской пол)
  50: пилот(мужской пол)
  51: пилотка(нарушение)
  52: блуза дл.рукав,юбка